# Human Tasks:
# 1. Configure Apple Developer account credentials in repository secrets
# 2. Set DEVELOPMENT_TEAM in repository secrets for code signing

# Implements CI/CD Pipeline requirement from Technical Specification/5.3.4 Infrastructure
name: iOS Build

# Configure workflow triggers for main and develop branches
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

# Environment configuration based on Technical Specification requirements
env:
  XCODE_VERSION: '14.0'
  IOS_DEPLOYMENT_TARGET: '15.0'
  SWIFT_VERSION: '5.5'
  SCHEME: 'MintReplicaLite'
  CONFIGURATION: 'Debug'
  PRODUCT_BUNDLE_IDENTIFIER: 'com.mintreplicaapp.ios'
  MARKETING_VERSION: '1.0.0'
  CURRENT_PROJECT_VERSION: '1'

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest
    
    steps:
    # Checkout repository code using actions/checkout@v3
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    # Setup Xcode environment using maxim-lobanov/setup-xcode@v1
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ env.XCODE_VERSION }}
    
    # Cache Swift Package Manager dependencies using actions/cache@v3
    - name: Cache Swift Packages
      uses: actions/cache@v3
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    
    # Build iOS application using xcodebuild
    - name: Build iOS App
      working-directory: src/ios
      env:
        DEVELOPER_DIR: /Applications/Xcode_${{ env.XCODE_VERSION }}.app/Contents/Developer
      run: |
        xcodebuild clean build \
          -scheme ${{ env.SCHEME }} \
          -configuration ${{ env.CONFIGURATION }} \
          -destination 'generic/platform=iOS' \
          SWIFT_VERSION=${{ env.SWIFT_VERSION }} \
          IPHONEOS_DEPLOYMENT_TARGET=${{ env.IOS_DEPLOYMENT_TARGET }} \
          MARKETING_VERSION=${{ env.MARKETING_VERSION }} \
          CURRENT_PROJECT_VERSION=${{ env.CURRENT_PROJECT_VERSION }} \
          PRODUCT_BUNDLE_IDENTIFIER=${{ env.PRODUCT_BUNDLE_IDENTIFIER }} \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
    
    # Archive build artifacts
    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ios-build
        path: |
          src/ios/build/Debug-iphoneos/*.app
          src/ios/build/Debug-iphoneos/*.dSYM
        retention-days: 5

    # Archive build logs
    - name: Archive Build Logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-logs
        path: |
          ~/Library/Developer/Xcode/DerivedData/**/Logs/Build
        retention-days: 5